# Generated by Django 3.1.4 on 2021-02-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('important', models.BooleanField(default=False)),
                ('dete_of_payment', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('dete_of_receveing', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
