# Generated by Django 3.1.4 on 2021-02-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='dete_of_payment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='dete_of_receveing',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
