# Generated by Django 3.1.4 on 2021-02-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210222_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='dete_of_payment',
        ),
        migrations.RemoveField(
            model_name='income',
            name='dete_of_receveing',
        ),
        migrations.AddField(
            model_name='expense',
            name='date_of_payment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='date_of_receiving',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
