# Generated by Django 3.1.4 on 2021-02-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210222_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='date_of_payment',
        ),
        migrations.RemoveField(
            model_name='income',
            name='date_of_receiving',
        ),
        migrations.AddField(
            model_name='expense',
            name='month',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='month',
            field=models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
