# Generated by Django 3.1.4 on 2021-02-26 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210223_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='reason',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Construction', 'Construction'), ('Medical', 'Medical'), ('Education', 'Education'), ('Electronics', 'Electronics'), ('Services', 'Services'), ('Gifts', 'Gifts'), ('Travel', 'Travel'), ('Kids', 'Kids'), ('Pet', 'Pet'), ('Others', 'Others')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='month',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
