# Generated by Django 3.1.4 on 2021-02-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='reason',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Construction', 'Construction'), ('Medical', 'Medical'), ('Education', 'Education'), ('Electronics', 'Electronics'), ('Services', 'Services'), ('Gifts', 'Gifts'), ('Travel', 'Travel'), ('Kids', 'Kids'), ('Furniture', 'Furniture'), ('Music', 'Music'), ('Pet', 'Pet'), ('Others', 'Others')], max_length=1000, null=True),
        ),
    ]
