# Generated by Django 3.1.4 on 2021-03-01 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_expense_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
    ]
