# Generated by Django 3.1.4 on 2021-03-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_expensewaste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensewaste',
            name='user',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='ExpenseWaste',
        ),
    ]
