# Generated by Django 3.1.4 on 2021-03-03 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0020_auto_20210302_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.FloatField()),
                ('reason', models.CharField(blank=True, choices=[('Home', 'Home'), ('Construction', 'Construction'), ('Medical', 'Medical'), ('Education', 'Education'), ('Electronics', 'Electronics'), ('Services', 'Services'), ('Gifts', 'Gifts'), ('Travel', 'Travel'), ('Kids', 'Kids'), ('Furniture', 'Furniture'), ('Music', 'Music'), ('Pet', 'Pet'), ('Others', 'Others')], max_length=1000, null=True)),
                ('important', models.BooleanField(default=False)),
                ('month', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='description',
        ),
    ]
